FROM node:18
WORKDIR /app
COPY package.json .
# COPY yarn.lock .
COPY tsconfig.json . 
COPY src ./src
COPY public ./public

RUN yarn install --ignore-engines

# Set the startup command for the container
CMD ["yarn", "start"]
