export enum Form {
  // TODO Think about joining MULTI, COMBI & ROUNDBAR into one
  COIN = "COIN",
  BAR = "BAR",
  KINEBAR = "KINEBAR",
  COMBIBAR = "COMBIBAR",
  ROUNDBAR = "ROUNDBAR",
  PACKET = "PACKET",
  MUNZBARREN = "MUNZBARREN",
  MULTICARD = "MULTICARD",
}